version: '3.9'

services:
  mongo40:
    image: mongo:4.0
    container_name: mongo40
    network_mode: "host"
    volumes:
      - ~/post-be-php-volume/mongodb:/data/db
      - ./local/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u root -p rootpass --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: ["--replSet", "rs0", "--bind_ip_all"]

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    network_mode: "host"
    volumes:
      - ./local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html

  post-be-php:
    build:
      context: .
      target: local
    container_name: post-be-php
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./local/xdebug:/usr/local/etc/php/conf.d/
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./tests:/var/www/tests
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
