<?php

declare(strict_types=1);

namespace Post\CommandModel;

enum ExceptionReference: String
{
    case INVALID_POST = 'INVALID_POST';
    case UNFIT_FOR_SEGMENT_USERNAME = 'UNFIT_FOR_SEGMENT_USERNAME';
    case UNFIT_FOR_SEGMENT_DURATION = 'UNFIT_FOR_SEGMENT_DURATION';
    case INVALID_JSON_FORMAT = 'INVALID_JSON_FORMAT';
    case INVALID_REPOST = 'INVALID_REPOST';
    case INVALID_QUOTE = 'INVALID_QUOTE';
    case INVALID_TEXT = 'INVALID_TEXT';
    case INVALID_UUID = 'INVALID_UUID';
    case INVALID_TIMESTAMP = 'INVALID_TIMESTAMP';  
    case MAX_LIMIT_REACHED = 'MAX_LIMIT_REACHED';
    case INVALID_JSON_SCHEMA = 'INVALID_JSON_SCHEMA';

}